import assert from 'node:assert/strict';
import {indexedDB} from 'fake-indexeddb';
import {build} from 'esbuild';
import {cp,mkdir} from 'node:fs/promises';
await mkdir('dist/test',{recursive:true});
await build({entryPoints:['scripts/browser-storage.mjs'],bundle:true,platform:'node',format:'esm',banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const __dirname=new URL('.',import.meta.url).pathname;"},outfile:'dist/test/storage.mjs'});
await cp('node_modules/sql.js/dist/sql-wasm.wasm','dist/test/sql-wasm.wasm');
globalThis.indexedDB=indexedDB;globalThis.location={origin:'https://hayleyw7.github.io'};
Object.defineProperty(globalThis,'navigator',{value:{locks:{request:async(name,fn)=>fn()}}});
const {request}=await import('../dist/test/storage.mjs');
const session=await request('/api/session');assert(session.storageReady);
const scene={version:2,creationId:crypto.randomUUID(),items:[{id:'fern',uid:crypto.randomUUID(),x:500,y:500,size:100,flip:false}],palette:'haunted',background:'cave',moon:'none',galaxy:'none',shootingStars:false,weather:[],seed:8921};
const call=(path,method,body)=>request(path,{method,body:JSON.stringify(body)});
await call('/api/draft','PUT',{scope:session.draftScope,editId:crypto.randomUUID(),scene});assert.deepEqual((await request('/api/draft')).draft.scene.items[0].id,'fern');
await call('/api/favorites','POST',{itemId:'fern',favorite:true});assert.deepEqual((await request('/api/favorites')).items,['fern']);
const id=crypto.randomUUID();await call('/api/drawings','POST',{id,collection:'album',title:'Cave',scene,thumbnail:'data:image/png;base64,'+Buffer.alloc(30).toString('base64')});
let album=await request('/api/drawings?collection=album');assert.equal(album.items.length,1);assert(album.items[0].thumbnail.startsWith('blob:'));assert.equal((await request('/api/drawings/'+id)).drawing.scene.background,'cave');
await call('/api/drawings/'+id,'PATCH',{title:'New Cave'});assert.equal((await request('/api/drawings?collection=album')).items[0].title,'New Cave');
const progress=await call('/api/achievements/sync','POST',{scope:session.draftScope});assert.equal(progress.savedCount,1);assert(progress.earned.some(x=>x.id==='first-sprout'));
const second=await import('../dist/test/storage.mjs?reload');assert.equal((await second.request('/api/drawings?collection=album')).items[0].title,'New Cave');
await call('/api/drawings/'+id,'DELETE',{confirmation:'permanently-delete',collection:'album',title:'New Cave'});assert.equal((await request('/api/drawings?collection=album')).items.length,0);
const historyId=crypto.randomUUID();await call('/api/drawings','POST',{id:historyId,collection:'history',scene,thumbnail:'data:image/png;base64,'+Buffer.alloc(30).toString('base64')});await call('/api/drawings/'+historyId+'/album','POST',{title:'From History'});assert.equal((await request('/api/drawings?collection=album')).items[0].title,'From History');
console.log('PASS: draft, favorites, album, thumbnail, rename, achievements, reload, deletion, history promotion.');
