import assert from 'node:assert/strict';
import {installPickerDrag} from '../public/picker-drag.js';
class Target{constructor(){this.listeners={};this.style={};this.children=[];this.attributes={};this.classList={contains:c=>this.classes?.includes(c),toggle(){}};}addEventListener(t,f){(this.listeners[t]??=[]).push(f);}emit(t,e={}){for(const f of this.listeners[t]||[])f(e);}contains(e){return e===button||e===handle;}setPointerCapture(){this.captured=true;}hasPointerCapture(){return this.captured;}releasePointerCapture(){this.captured=false;}setAttribute(k,v){this.attributes[k]=v;}append(x){this.children.push(x);}remove(){this.removed=true;}}
const picker=new Target(),doc=new Target(),win=new Target(),button=new Target(),handle=new Target();button.classes=['stamp'];handle.classes=['stamp-drag-handle'];button.dataset=handle.dataset={id:'bunny'};doc.body=new Target();doc.createElement=()=>new Target();win.innerHeight=800;win.requestAnimationFrame=()=>1;win.cancelAnimationFrame=()=>{};win.scrollBy=()=>{};
let bounds={left:100,top:100,width:600,height:540,right:700,bottom:640},allowed=true,placements=[];
installPickerDrag({picker,canvas:{getBoundingClientRect:()=>bounds},canStart:()=>allowed,preview:()=>({src:'data:image/png,test',width:100,height:80}),place:(...p)=>placements.push(p),doc,win});
function event(target=button,x=800,y=200,type='mouse'){return{target:{closest:()=>target},clientX:x,clientY:y,pointerId:1,pointerType:type,isPrimary:true,button:0,detail:1,preventDefault(){this.prevented=true;},stopImmediatePropagation(){this.stopped=true;},stopPropagation(){this.stopped=true;}};}
let e=event();picker.emit('pointerdown',e);doc.emit('pointerup',e);const click=event();doc.emit('click',click);assert(!click.prevented);assert.equal(placements.length,0,'Ordinary click remains the normal add handler’s responsibility');
picker.emit('pointerdown',event());doc.emit('pointermove',event(button,400,370));assert.equal(doc.body.children.length,1);assert.equal(placements.length,0,'Preview must not alter scene');doc.emit('pointerup',event(button,400,370));assert.deepEqual(placements,[['bunny',.5,.5]]);assert(doc.body.children[0].removed);e=event();doc.emit('click',e);assert(e.stopped,'Drag must suppress generated click');
picker.emit('pointerdown',event());doc.emit('pointermove',event(button,300,200));doc.emit('pointerup',event(button,800,200));assert.equal(placements.length,1,'Outside drop cancels');
picker.emit('pointerdown',event());doc.emit('pointermove',event(button,300,200));doc.emit('keydown',{key:'Escape',preventDefault(){},stopPropagation(){}});doc.emit('pointerup',event(button,300,200));assert.equal(placements.length,1);
bounds={left:20,top:40,width:300,height:270,right:320,bottom:310};picker.emit('pointerdown',event());doc.emit('pointermove',event(button,95,242.5));doc.emit('pointerup',event(button,95,242.5));assert.deepEqual(placements.at(-1),['bunny',.25,.75],'Use current canvas bounds after scaling/scroll');
const before=placements.length;picker.emit('pointerdown',event(button,100,100,'touch'));doc.emit('pointermove',event(button,150,150,'touch'));doc.emit('pointerup',event(button,150,150,'touch'));assert.equal(placements.length,before,'Touch card swipe remains native scrolling');
picker.emit('pointerdown',event(handle,400,400,'touch'));doc.emit('pointermove',event(handle,170,175,'touch'));doc.emit('pointerup',event(handle,170,175,'touch'));assert.deepEqual(placements.at(-1),['bunny',.5,.5]);
picker.emit('pointerdown',event());doc.emit('pointermove',event(button,150,150));const count=placements.length;doc.emit('pointercancel',event());doc.emit('pointerup',event(button,150,150));assert.equal(placements.length,count);
picker.emit('pointerdown',event());doc.emit('pointermove',event(button,150,150));allowed=false;doc.emit('pointerup',event(button,150,150));assert.equal(placements.length,count,'Busy state cannot commit an in-flight drag');
console.log('PASS: picker click, drag preview, one drop, duplicate-click suppression, zoom/scroll coordinates, outside/Escape/pointercancel, touch scroll/handle, busy cancellation');
