import {mkdir,rm,cp,readFile,writeFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {welcomePage,sharingMetadata} from './welcome-page.mjs';
await rm('dist',{recursive:true,force:true});
await cp('public','dist',{recursive:true});
const editor=(await readFile('public/index.html','utf8')).replace(/<meta name="description"[^>]*>/g,'').replace('</head>',sharingMetadata+'</head>');
await writeFile('dist/editor.html',editor);
await writeFile('dist/index.html',await welcomePage().text());
const gardenSource=await readFile('public/garden.js','utf8');
const catalogue= gardenSource.slice(gardenSource.indexOf('const catalog='),gardenSource.indexOf('const customRects='));
await writeFile('scripts/browser-catalog.json',JSON.stringify([...catalogue.matchAll(/id:'([^']+)'/g)].map(x=>x[1])));
const journal=JSON.parse(await readFile('drizzle/meta/_journal.json','utf8'));
await writeFile('scripts/browser-migrations.json',JSON.stringify(await Promise.all(journal.entries.map(x=>readFile('drizzle/'+x.tag+'.sql','utf8')))));
await build({entryPoints:['scripts/browser-storage.mjs'],bundle:true,format:'esm',platform:'browser',outfile:'dist/browser-storage.js',external:['fs','path','crypto'],minify:true});
await cp('node_modules/sql.js/dist/sql-wasm.wasm','dist/sql-wasm.wasm');
await writeFile('dist/.nojekyll','');
console.log('Built static GitHub Pages site in dist/. All saves stay in the browser.');
