// Public showcase uses only bundled scenery, never account creations.
const examples=[
  {image:'bg-cave.webp',name:'Cave'},
  {image:'bg-graveyard-v5.webp',name:'Graveyard'},
  {image:'bg-space-v2.webp',name:'Space'}
];
export const publicPreviewPaths=new Set(examples.map(x=>'/assets/'+x.image));
export function welcomePage(signedIn){return new Response(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#23192b"><script>try{if(localStorage.getItem('whimsy-grove-visited:'+new URL('.',location.href).pathname)==='1')location.replace('editor.html');}catch{}</script><title>Whimsy Grove · Scene builder</title><meta name="description" content="Build scenes with illustrated landscapes, plants, creatures, and weather."><style>
*{box-sizing:border-box}html{color-scheme:dark;scroll-behavior:smooth}body{margin:0;background:#23192b;color:#faf3f3;font:16px/1.6 system-ui,sans-serif}a{color:inherit}a:focus-visible{outline:3px solid #edc0fc;outline-offset:6px}header,main,footer{max-width:1160px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-weight:750;letter-spacing:-.04em;font-size:22px;text-decoration:none}.signin{font-size:14px;text-underline-offset:5px}.hero{max-width:760px;padding:65px 0 58px}.eyebrow{color:#d2b8dd;font-size:12px;letter-spacing:.18em;text-transform:uppercase;font-weight:700}h1{font-family:Georgia,serif;font-size:clamp(44px,7vw,78px);line-height:1.06;letter-spacing:-.045em;margin:20px 0 26px;font-weight:500}h1 em{color:#d9b2e9;font-weight:400}.intro{max-width:540px;color:#d9cddd;font-size:18px}.actions{display:flex;align-items:center;gap:24px;flex-wrap:wrap;margin-top:30px}.button{display:inline-block;background:#e6c2ef;color:#291c30;padding:13px 24px;border-radius:999px;text-decoration:none;font-weight:700}.button:hover{background:#f4ddfa}.secondary{text-underline-offset:5px;font-size:14px}.note{color:#bfaec6;font-size:13px;margin-top:16px}.section-heading{display:flex;justify-content:space-between;align-items:baseline;gap:16px;flex-wrap:wrap}h2{font-family:Georgia,serif;font-size:29px;font-weight:400;margin:0}.section-heading p{font-size:13px;color:#bfaec6}.examples{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin:20px 0 60px}figure{margin:0;background:#302338;border:1px solid #4b3654;border-radius:18px;overflow:hidden}figure img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}figcaption{padding:19px}h3{margin:0 0 6px;font-size:17px}figcaption p{margin:0;color:#cbbbd2;font-size:14px}.closing{border-top:1px solid #4b3654;padding:32px 0;display:flex;justify-content:space-between;align-items:center;gap:24px;flex-wrap:wrap}.closing p{color:#cbbbd2;margin:6px 0}footer{font-size:12px;color:#bfaec6;padding-bottom:35px}@media(max-width:680px){.hero{padding-top:35px}.examples{grid-template-columns:1fr;gap:24px}figure img{aspect-ratio:16/10}header,main,footer{padding-left:20px;padding-right:20px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
</style></head><body><header><a href="./" class="brand">Whimsy Grove</a><a class="signin" href="editor.html">Open editor</a></header><main><section class="hero"><h1>Somewhere to put your<br><em>weird little guys.</em></h1><p class="intro">Create a whimsical scene with plants, creatures, weather, and whatever else belongs there.</p><div class="actions"><a class="button" href="editor.html">${signedIn?'Open your grove':'Create your grove'}</a><a class="secondary" href="#examples">Preview landscapes ↓</a></div><p class="note">Saved in this browser only. No account or syncing. Clearing site data removes your saves.</p></section><section id="examples" aria-labelledby="examples-title"><div class="section-heading"><h2 id="examples-title">Choose your setting</h2><p>Three of the available landscapes</p></div><div class="examples">${examples.map(x=>`<figure><img src="assets/${x.image}" alt="${x.name}" width="640" height="480"><figcaption><h3>${x.name}</h3></figcaption></figure>`).join('')}</div></section></main></body></html>`,{headers:{'content-type':'text/html; charset=utf-8'}});}
