// First-visit welcome. Returning visitors reopen their browser-saved grove.
const siteUrl='https://hayleyw7.github.io/whimsy-grove/';
const description='Feeling whimsical? Create your own grove art!';
export const pageTitle='Whimsy Grove | Create Your Own Cozy Scene Art';
export const sharingMetadata=`<meta name="description" content="${description}">
<link rel="canonical" href="${siteUrl}">
<meta property="og:type" content="website"><meta property="og:site_name" content="Whimsy Grove"><meta property="og:title" content="${pageTitle}"><meta property="og:description" content="${description}"><meta property="og:url" content="${siteUrl}">
<meta property="og:image" content="${siteUrl}assets/whimsy-grove-preview-v2.jpg"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="A tuxedo cat, pink sleeping bunny, alien, and ghost gathered with a lantern, mushroom, and fern above the Whimsy Grove name.">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${pageTitle}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${siteUrl}assets/whimsy-grove-preview-v2.jpg"><meta name="twitter:image:alt" content="Whimsy Grove with a tuxedo cat, pink bunny, alien, ghost, lantern, mushroom, and fern.">`;
// Direct editor links must honor the same first-visit flow as the site root.
// The welcome CTA carries a one-use navigation signal, removed before bookmarking.
export const editorEntryScript=`<script>try{const url=new URL(location.href);if(url.searchParams.get('start')==='1'){url.searchParams.delete('start');history.replaceState(null,'',url.pathname+url.search+url.hash);}else if(localStorage.getItem('whimsy-grove-visited:'+new URL('.',url).pathname)!=='1'){location.replace('./');}}catch{}</script>`;
export function welcomePage(){return new Response(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#23192b"><title>${pageTitle}</title>${sharingMetadata}<script>try{if(!new URL(location.href).searchParams.has('welcome')&&localStorage.getItem('whimsy-grove-visited:'+new URL('.',location.href).pathname)==='1')location.replace('editor.html');}catch{}</script><script>try{const preference=JSON.parse(localStorage.getItem('spooky-grove-motion-v1')||'null'),enabled=typeof preference==='boolean'?preference:!matchMedia('(prefers-reduced-motion: reduce)').matches;if(enabled){document.documentElement.classList.add('welcome-loading');window.welcomeRevealTimer=setTimeout(()=>document.documentElement.classList.remove('welcome-loading'),4500);}}catch{if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('welcome-loading');window.welcomeRevealTimer=setTimeout(()=>document.documentElement.classList.remove('welcome-loading'),4500);}}</script><script type="module" src="welcome.js"></script><style>
*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;background:#23192b;color:#faf3f3;font:1rem/1.5 system-ui,sans-serif;min-height:100vh;min-height:100svh;display:grid;place-items:center;padding:max(16px,env(safe-area-inset-top)) max(16px,env(safe-area-inset-right)) max(16px,env(safe-area-inset-bottom)) max(16px,env(safe-area-inset-left))}main{width:100%;max-width:600px;display:flex;flex-direction:column;align-items:center;gap:clamp(20px,3svh,28px);text-align:center}h1{margin:0;font-family:Georgia,serif;font-size:clamp(2rem,7vw,3.5rem);font-weight:500;line-height:1.12;letter-spacing:-.035em}.grove{position:relative;width:min(84vw,19rem);max-width:100%;aspect-ratio:290/160;isolation:isolate}.sprite{position:absolute;background-repeat:no-repeat;aspect-ratio:1;bottom:0}.fern{background-image:url('assets/woodland.webp');background-size:300% 300%;background-position:0 0;width:31%;left:1%;bottom:3%;transform:rotate(-10deg)}.mushroom{background-image:url('assets/mushrooms.webp');background-size:300% 200%;background-position:0 0;width:20%;right:0;bottom:-5%;z-index:1}.cat{background-image:url('assets/cats-consistent-v27.webp');background-size:349.2126% 122.3448%;background-position:100% 61.7284%;aspect-ratio:508/725;width:24%;left:12%;bottom:3%;z-index:2}.bone{background-image:url('assets/props-bones-v5.webp');background-size:752.9412% 412.9032%;background-position:24.3243% 67.0103%;aspect-ratio:170/310;width:5%;left:10%;bottom:1%;transform:rotate(72deg);z-index:4}.bunny{background-image:url('assets/bunny-revisions-v2.webp');background-size:300% 100%;background-position:0 0;width:37%;right:26%;bottom:-12%;z-index:3}.alien{background-image:url('assets/rituals.webp');background-size:312.1951% 312.1951%;background-position:97.0115% 48.9655%;aspect-ratio:1;width:28%;right:10%;bottom:1%;z-index:2}.ghost{background-image:url('assets/visitors.webp');background-size:300% 200%;background-position:0 100%;width:23%;left:36%;bottom:43%}.lantern{background-image:url('assets/rituals.webp');background-size:411.5756% 305.4893%;background-position:49.1228% 0;aspect-ratio:311/419;width:13%;left:33%;bottom:0;z-index:4}.button{display:inline-flex;align-items:center;justify-content:center;min-height:50px;padding:12px 30px;border:1px solid #f0d2f5;border-radius:999px;background:#e6c2ef;color:#291c30;text-decoration:none;font-weight:650;box-shadow:0 4px 20px #120d1933}.button:hover{background:#f1d7f7}.button:focus-visible{outline:3px solid #faf3f3;outline-offset:6px}.button:active{background:#d8addf}@media(max-width:650px){.grove{aspect-ratio:190/145}.ghost{bottom:35%}}
.welcome-loading .sprite,.welcome-enter .sprite{opacity:0;translate:0 9px;transition:opacity .34s ease-out,translate .42s cubic-bezier(.2,.7,.2,1)}.welcome-enter .sprite.is-visible{opacity:1;translate:0 0}.ghost{--arrival:0ms}.fern{--arrival:350ms}.mushroom{--arrival:700ms}.cat{--arrival:1050ms}.alien{--arrival:1400ms}.bunny{--arrival:1750ms}.lantern{--arrival:2100ms}.bone{--arrival:2450ms}.welcome-enter .bunny{filter:url(#bunnyEarTwitch)}.welcome-enter .ghost.is-visible{animation:ghost-float 6s ease-in-out infinite}@keyframes ghost-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}.welcome-enter .lantern.is-visible::after{content:"";position:absolute;left:30%;top:33%;width:40%;height:30%;border-radius:50%;background:#ffd98b;box-shadow:0 0 18px 8px #ffd98b88;filter:blur(5px);mix-blend-mode:screen;pointer-events:none;opacity:.52;animation:lantern-glow 3.6s ease-in-out 450ms infinite}@keyframes lantern-glow{0%,12%,100%{opacity:.52}14%{opacity:.2}16%{opacity:.72}18%{opacity:.3}21%{opacity:.64}24%{opacity:.27}27%{opacity:.5}70%{opacity:.5}72%{opacity:.22}74%{opacity:.7}76%{opacity:.32}79%{opacity:.55}}.welcome-paused .ghost,.welcome-paused .lantern::after{animation-play-state:paused}
</style></head><body><svg id="welcomeEarMotion" width="0" height="0" aria-hidden="true" focusable="false" style="position:absolute"><defs><filter id="bunnyEarTwitch" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB"><feImage href="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20512%20512%22%3E%3Cdefs%3E%3Cfilter%20id%3D%22soft%22%3E%3CfeGaussianBlur%20stdDeviation%3D%225%22%2F%3E%3C%2Ffilter%3E%3C%2Fdefs%3E%3Crect%20width%3D%22512%22%20height%3D%22512%22%20fill%3D%22rgb%28128%2C128%2C128%29%22%2F%3E%3Cpath%20d%3D%22M210%20345%20Q198%20289%20239%20213%20L282%20179%20Q298%20191%20283%20242%20L277%20303%20Q262%20352%20228%20358%20Z%22%20fill%3D%22rgb%28255%2C128%2C128%29%22%20filter%3D%22url%28%23soft%29%22%2F%3E%3C%2Fsvg%3E" result="earMap" preserveAspectRatio="none"/><feDisplacementMap in="SourceGraphic" in2="earMap" scale="0" xChannelSelector="R" yChannelSelector="G"><animate attributeName="scale" begin="indefinite" values="0;12;0;8;0" keyTimes="0;.25;.5;.75;1" dur=".55s" fill="remove"/></feDisplacementMap></filter></defs></svg><main><div class="grove" aria-hidden="true"><span class="sprite fern"></span><span class="sprite mushroom"></span><span class="sprite bone"></span><span class="sprite cat"></span><span class="sprite bunny"></span><span class="sprite alien"></span><span class="sprite ghost"></span><span class="sprite lantern"></span></div><h1>Whimsy Grove</h1><a class="button" href="editor.html?start=1" aria-label="Create">Create</a></main></body></html>`,{headers:{'content-type':'text/html; charset=utf-8'}});}
